## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true
  ## Prometheus-operator image
  ##
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-operator
    # if not set appVersion field from Chart.yaml is used
    tag: main
    sha: ""
    pullPolicy: IfNotPresent
prometheus:
  prometheusSpec:
    ## scrapeConfigs to be selected for target discovery.
    ## If {}, select all scrapeConfigs
    ##
    ## Example which selects scrapeConfigs with label "prometheus" set to "somelabel"
    scrapeConfigSelector:
      matchLabels:
        prometheus: somelabel

    ## If nil, select own namespace. Namespaces to be selected for scrapeConfig discovery.
    ## If null, exclude the field from the prometheusSpec (keeping downward compatibility with older versions of CRD)
    scrapeConfigNamespaceSelector: {}
    ## Example which selects scrapeConfig in namespaces with label "prometheus" set to "somelabel"
    # scrapeConfigNamespaceSelector:
    #   matchLabels:
    #     prometheus: somelabel
