apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-***REMOVED***
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pve-***REMOVED***
  template:
    metadata:
      labels:
        app: pve-***REMOVED***
    spec:
      containers:
        - name: pve-***REMOVED***
          image: prompve/prometheus-pve-***REMOVED***:latest
          ports:
            - containerPort: 9221
          env:
            - name: TOKEN_NAME
              valueFrom:
                secretKeyRef:
                  name: pve-secret
                  key: token_name
            - name: TOKEN_VALUE
              valueFrom:
                secretKeyRef:
                  name: pve-secret
                  key: token_value
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
              subPath: pve.yml
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: pve-configmap
            items:
              - key: pve.yml
                path: pve.yml