apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-***REMOVED***
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pve-***REMOVED***
  template:
    metadata:
      labels:
        app: pve-***REMOVED***
    spec:
      containers:
        - name: pve-***REMOVED***
          image: prompve/prometheus-pve-***REMOVED***:latest
          ports:
            - containerPort: 9221
              name: http
          env:
            - name: PVE_TOKEN_NAME
              valueFrom:
                secretKeyRef:
                  name: pve-secret
                  key: token_name
            - name: PVE_TOKEN_VALUE
              valueFrom:
                secretKeyRef:
                  name: pve-secret
                  key: token_value
          envFrom:
            - configMapRef:
                name: pve-configmap
      restartPolicy: Always