apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pve-monitor
resources:
  - namespace.yaml
  - pve-secret.yaml
  - configmap.yaml
  - deployment.yaml
  - pve-service.yaml
  - pve-servicemonitor.yaml