apiVersion: v1
kind: Service
metadata:
  name: pve-***REMOVED***
  namespace: pve-monitor
  labels:
    app: pve-***REMOVED***
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: pve-monitor