---
apiVersion: v1
kind: Service
metadata:
  name: pve-***REMOVED***-service
spec:
  selector:
    app: pve-***REMOVED***
  ports:
    - port: 9221
      targetPort: 9221
      protocol: TCP
      name: http
  type: ClusterIP