apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pve-***REMOVED***
  namespace: pve-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: pve-***REMOVED***
  endpoints:
  - port: http
    interval: 30s
    path: /pve